export default [
  { name: 'Susan Aitken', description: 'Leader of Glasgow City Council' },
  { name: 'Derek Alton', description: 'Passionate advocate for improving government, digital transformation with the Government of Canada and Civic Punk' },
  { name: 'Geoff Ballinger', description: 'Startup technologist' },
  { name: 'Anna Burnside', description: 'Journalist, journalism lecturer, humanist celebrant.' },
  { name: 'Nia Campbell', description: 'Co-author of Transform Wales' },
  { name: 'Jo Carter', description: 'Co-author of Transform Wales' },
  { name: 'Stephen Coleman OBE', description: 'CEO and Co-founder of CodeBase' },
  { name: 'Alex Coley', description: 'Data Strategy and Tech Leader, ex-Defra, ex-Welsh Government Brexit Advisory Group' },
  { name: 'Sid Dutta', description: '' },
  { name: 'David Durant', description: 'Long time civic tech organiser' },
  { name: 'Jerry Fishenden', description: 'Seasoned digital professional with extensive experience of delivering better organisations and outcomes in both public and private sectors.' },
  { name: 'Alan Fowler', description: 'Retired business person with special experience in making futures happen.' },
  { name: 'Gavin Freeguard', description: 'Director, State of the Future' },
  { name: 'Gordon Guthrie', description: 'Founder, Tech Executive, ex-Research Fellow at Scottish Government' },
  { name: 'Joe Halliwell', description: 'Old time AI founder currently in large financial institution' },
  { name: 'Keith Harrison', description: 'Software developer' },
  { name: 'Michael Hayes', description: 'Founder' },
  { name: 'Jenni Hislop', description: 'Senior Health Economist' },
  { name: 'Kate Ho', description: 'Technology generalist with expertise in product, engineering and data' },
  { name: 'Karina Kangur', description: 'Data professional' },
  { name: 'Ann Kempster', description: 'Co-author of Transform Wales' },
  { name: 'Iain Kennedy', description: 'Product management leader and tech executive' },
  { name: 'Caroline Laurenson', description: 'Tech entrepreneur, non-executive director in the education sector and STEM ambassador' },
  { name: 'Gabi Lipan', description: 'Programme Director - Education' },
  { name: 'Vijay Luthra', description: 'Public service reform, state capacity and mission delivery expert' },
  { name: 'Jamie McHale', description: 'Technologist, freelance consultant and developer building communities across Scotland.' },
  { name: 'Nadia McKay', description: 'Female founder, ex-corporate, now mentor' },
  { name: 'Mike McQuaid', description: 'CTO, software engineer and open source maintainer' },
  { name: 'Karen Meechan', description: 'CEO ScotlandIS' },
  { name: 'Daniel Opeyemi', description: 'Student, University of Strathclyde' },
  { name: 'Craig Parker', description: 'CEO, co-founder and career technical leader' },
  { name: 'Kaya Pelczar', description: 'Inclusive digital product design consultant' },
  { name: 'Richard Pope', description: 'Independent consultant and author' },
  { name: 'Paul Reilly', description: 'Academic specialising in social media and contentious politics, digital activism and peacebuilding' },
  { name: 'Simon Roberts', description: 'Data specialist, Scottish Local Government' },
  { name: 'Edward Saperia', description: 'Dean of the London College of Political Technology' },
  { name: 'Craig Somerville', description: 'Founder at a SaaS AI company and TechScaler founder' },
  { name: 'John McTernan', description: 'Political strategist' },
  { name: 'Dafydd Vaughan', description: 'Co-author of Transform Wales' },
  { name: 'Robert Walker', description: 'Technologist; had inputs to Scotland\'s AI strategy' },
  { name: 'Hugh Wallace', description: 'Technologist working across the public sector; citizen with a keen interest in how digital tools and technology can benefit us all.' },
  { name: 'Tom Wardell', description: 'Head of Partnerships for a SaaS platform' },
  { name: 'Andy Williams', description: 'Chair ScotlandIS' },
  { name: 'Jessica Williamson', description: 'Director of Industry Innovation Ltd, innovation consultant' }, { name: 'Daniel Winterstein', description: 'Tech entrepreneur' },
];
